import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import BaseLayoutContent from "@/components/layout/BaseLayoutContent/BaseLayoutContent";

import "@/styles/globals.scss";

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <BaseLayoutContent>{children}</BaseLayoutContent>
      </body>
    </html>
  );
}
